version: "3.3"

services:
  one-c:
    restart: always
    env_file: .test.env
    build:
      context: .
    image: enterprise-service-bus
    deploy:
      resources:
        limits:
          memory: 512M
      mode: replicated
      replicas: 1
    environment:
      SERVICES: one-c
    networks:
      - internal

  puller:
    restart: always
    env_file: .test.env
    build:
      context: .
    image: enterprise-service-bus
    deploy:
      resources:
        limits:
          memory: 128M
      mode: replicated
      replicas: 1
    environment:
      SERVICES: puller
    networks:
      - internal

networks:
  internal:

volumes:
  data:
